### ISSUE TITLE
Issues with full LTO

### ISSUE THREAD

**Issue by nathanchance** [ClangBuiltLinux/continuous-integration2#104]
I have not done any triage yet but I believe the switch from ThinLTO to full LTO in android-5.10 has caused all of our builds to start failing:

https://android-review.googlesource.com/c/kernel/common/+/1621945

https://github.com/ClangBuiltLinux/continuous-integration2/actions/runs/634065920

Full LTO is single threaded and requires way more memory, which appears to be the cause of the failure because there is just a "Killed" message in the logs. If we want to continue testing android-5.10, I am guessing we will need to switch back over to ThinLTO or seeing if there is any way to up the memory limits on the TuxSuite side. I will try to build these configs within the next couple days to see what the maximum memory use is.

**Comment by nickdesaulniers** [comment]
oops, I didn't notice this before filing #105 (sorry). Since we already have comments there, let's close this one out and track there.
