### ISSUE TITLE
socat-external[597025] E connect(5, AF=2 127.0.0.1:4226, 16): Connection refused

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/continuous-integration2#119]
quite a few of our mainline builds are failing with thousands of errors like:
```
2021/04/13 13:19:23 socat-external[597018] E connect(5, AF=2 127.0.0.1:4226, 16): Connection refused
error: failed to execute compile
caused by: Failed to send data to or receive data from server
caused by: Failed to read response header
caused by: failed to fill whole buffer
```
this looks like an issue with tuxsuite? cc @terceiro @ivoire

**Comment by nickdesaulniers** [comment]
cc @vishalbhoj

**Comment by nathanchance** [comment]
https://gitlab.com/Linaro/tuxmake/-/issues/131

**Comment by vishalbhoj** [comment]
I have marked these failures as infrastructure errors while we work on a real fix for it. This will allow the cli to retry on such failure and finish correctly instead of marking them as build failures.

**Comment by vishalbhoj** [comment]
The issue happens on specific build configuration and retrying doesn't help. I have reverted tuxmake back to older version where we don't get this error while we investigate the issue.

**Comment by nathanchance** [comment]
The upstream issue says this has been resolved.
