### ISSUE TITLE
ppc32 builds not booting on next

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/continuous-integration2#121]
something in next seems to have caused 32b PPC to stop booting
https://github.com/ClangBuiltLinux/continuous-integration2/runs/2388901919?check_suite_focus=true

**Comment by nathanchance** [comment]
https://github.com/ClangBuiltLinux/linux/issues/1345#issuecomment-816864777

**Comment by nickdesaulniers** [comment]
aye, I need to stop filing issues in this repo and instead focus on our existing issue tracker.
