### ISSUE TITLE
add problem matcher

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/continuous-integration2#122]
@nathanchance noticed that https://github.com/linuxppc/linux-ci/actions/runs/774767088 has some neat warning reports in github itself. Looks like:
https://github.com/actions/toolkit/blob/master/docs/problem-matchers.md is being used
cc @mpe

**Comment by nathanchance** [comment]
I should be able to explore this either tomorrow or next week.

**Comment by mpe** [comment]
I didn't find much good documentation on it.

My version was cribbed from various places including:
https://github.com/microsoft/vscode-cpptools/blob/main/Extension/package.json#L98

**Comment by mpe** [comment]
Obviously feel free to copy it:
https://github.com/linuxppc/linux-ci/blob/merge/.github/problem-matchers/gcc.json

**Comment by ojeda** [comment]
Thanks! That can be helpful also for Rust for Linux.
