### ISSUE TITLE
arm64 defconfig + full LTO failure

### ISSUE THREAD

**Issue by nathanchance** [ClangBuiltLinux/continuous-integration2#128]
https://github.com/ClangBuiltLinux/continuous-integration2/runs/2494932409?check_suite_focus=true

I am trying to reproduce locally so that I can see if this is something caused by LLVM or Linux (I suspect the former because LLVM 12 and older is fine).

**Comment by samitolvanen** [comment]
I see the same issue, but haven't had a chance to bisect this yet. LLVM monorepo commit `b535459d0a1db37fca6688b8e15305e361debff5` was the last one that booted for me, and the first failure I saw was with `8fc5f07fc0aee95ff9f79e91035d115690177dc1`, so something regressed between those two.

**Comment by nathanchance** [comment]
I am running an automated bisection now, just takes forever because full LTO... will post the results in the morning.

**Comment by nathanchance** [comment]
Might as well track in the main issue tracker: https://github.com/ClangBuiltLinux/linux/issues/1368
