### ISSUE TITLE
Wire up Android clang builds?

### ISSUE THREAD

**Issue by nathanchance** [ClangBuiltLinux/continuous-integration2#129]
TuxMake and TuxSuite are [gaining support](https://gitlab.com/Linaro/tuxsuite/-/issues/105) for [AOSP's `clang`](https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/).

Should we wire this up into CI? If so, what should we build with it?

Android branches probably are not of the highest priority given that is what it is being tested against right now. -next, mainline, and maybe latest LTS?

**Comment by nickdesaulniers** [comment]
> Should we wire this up into CI?

Yes.

> If so, what should we build with it?

Android kernels.  I'd like cut Android kernels over to just be built with AOSP LLVM, though I guess that wont help us catch regressions from LLVM.

**Comment by nathanchance** [comment]
> > If so, what should we build with it?
> 
> Android kernels. I'd like cut Android kernels over to just be built with AOSP LLVM, though I guess that wont help us catch regressions from LLVM.

We could build Android kernels with AOSP's LLVM and LLVM ToT, since AOSP's LLVM is always behind LLVM ToT.

It might be wise to build linux-next with AOSP's LLVM so that we can see if any new code is going to break android-mainline.

**Comment by stephenhines** [comment]
I agree with @nathanchance in the previous comment that ideally we run with both AOSP and ToT LLVM for any kernel build that we care about (which sounds like current Android kernel sources + linux-next).
