### ISSUE TITLE
set CROSS_COMPILE_COMPAT=arm-linux-gnueabi- for arm64 builds

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/continuous-integration2#133]
we should be testing the compat vdsos on ARCH=arm64 by setting that env var

**Comment by nathanchance** [comment]
This will require support in TuxSuite: https://gitlab.com/Linaro/tuxsuite/-/issues/108

**Comment by nickdesaulniers** [comment]
sounds like this is implemented?
https://gitlab.com/Linaro/tuxsuite/-/issues/108
