### ISSUE TITLE
Enable arm64 big endian for AOSP LLVM

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/continuous-integration2#141]
https://github.com/ClangBuiltLinux/continuous-integration2/runs/2655483207?check_suite_focus=true

**Comment by nathanchance** [comment]
Looks like this will be resolved with [clang-r428724 ](https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+/e9db902a03d1e9869c3b578aa9625a6a1154b89d). Once that has been enabled in Tux{Make,Suite}, we can enable it.

**Comment by nathanchance** [comment]
I have pushed https://gitlab.com/Linaro/tuxmake/-/merge_requests/224. Once that is merged and the image is updated, we can enable this and close the issue.
