### ISSUE TITLE
Notating "failed but unrelated to ClangBuiltLinux" builds

### ISSUE THREAD

**Issue by nathanchance** [ClangBuiltLinux/continuous-integration2#143]
This issue is to facilitate discussions around how we should notate builds that have failed for reasons unrelated to this project.

For example, there is currently [a big failure](https://lore.kernel.org/linux-next/20210527152631.1e70fba2@canb.auug.org.au/
) in -next around module dependencies, which impacts most of our builds of -next: https://github.com/ClangBuiltLinux/continuous-integration2/actions/runs/884962100

Should we have some sort of standard for marking these builds as "red but not something we need to be concerned about"? Maybe a pinned issue that we comment on, saying "I triaged this build failure, it was not related to us, not worth opening an issue over"? Or should we just open an issue in the main tracker and have a label that says "Not CBL related but opening for visibility"? I am personally subscribed to the linux-next mailing list so I am aware of issues like this but not everyone is.

**Comment by nathanchance** [comment]
We could open up the discussions section of GitHub for this.

**Comment by nickdesaulniers** [comment]
probably worth discussing at plumbers; we have our hands full with CBL, so I think maintaining an overall bug tracker for -next would spread us too thin.

**Comment by nathanchance** [comment]
I am going to close this up for now. We have not run into this too much and when we do, we can just close whatever issue gets opened from it with a link to an upstream bug report.
