### ISSUE TITLE
hexagon allmodconfig

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/continuous-integration2#152]
cc @nathanchance

**Comment by nathanchance** [comment]
Found another crash with `CONFIG_INIT_STACK_NONE=y`: https://github.com/ClangBuiltLinux/linux/issues/1410

**Comment by nathanchance** [comment]
One more outstanding issue: https://lore.kernel.org/r/20210708233849.3140194-1-nathan@kernel.org/

**Comment by nathanchance** [comment]
This should be possible soon, as Andrew Morton picked up my latest series: https://lore.kernel.org/r/20211115174250.1994179-1-nathan@kernel.org/

I think it is worth doing this for the latest LTS (5.15), mainline, and -next.
