### ISSUE TITLE
riscv allyesconfig

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/continuous-integration2#165]
while trying to repro https://github.com/ClangBuiltLinux/linux/issues/1409, I found I was able to build riscv allyesconfig without error with LLVM=1 LLVM_IAS=1.

**Comment by nathanchance** [comment]
Blocked on https://github.com/ClangBuiltLinux/linux/issues/1431 for `clang-nightly`.

**Comment by nickdesaulniers** [comment]
should be all set now for clang-13 and clang-14

**Comment by nathanchance** [comment]
https://apt.llvm.org was broken for a bit and the TuxMake images are not updated with it yet. Once they are updated, I will merge #173.
