### ISSUE TITLE
more 32b ARM targets

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/continuous-integration2#166]
I think at this point, we can build more of the 32b ARM configs. If so, we should start adding CI coverage for them, or filing bugs for whatever is still broken. Perhaps the CI for these can run less frequently?

**Comment by nathanchance** [comment]
I emailed Arnd for his input on testing more configurations: https://groups.google.com/g/clang-built-linux/c/Yw96d3xLg00/m/vhxbBoxvBAAJ

**Comment by arndb** [comment]
I would suggest adding

* omap2plus_defconfig (multiple v6/v7 levels)
* imx_v4_v5_defconfig (another v4/v5 config, if it builds)
* pxa3xx_defconfig (something with xscale)
* multi_v7_defconfig + LPAE + UNWINDER_FRAME_POINTER

The last one can probably be combined with the thumb2 config

I suppose we can actually drop the allyesconfig build, as that doesn't offer
much coverage beyond what allmodconfig has, but it takes much longer.

**Comment by nickdesaulniers** [comment]
allyesconfig takes longer to build than allmodconfig? If that's due to link time of vmlinux, I bet using LLD doesn't make the differences as obvious.

**Comment by nathanchance** [comment]
Yes, I am guessing that would be the main reason for it being longer. My personal build tests show `ARCH=arm64 allmodconfig` takes 11m 13s whereas `ARCH=arm64 allmodconfig` takes 12m 33s. `ARCH=arm allmodconfig` takes 8m 45s and `ARCH=arm allyesconfig` takes 9m 55s.

**Comment by nathanchance** [comment]
`pxa3xx_defconfig` is broken but it does not appear `clang` related: https://builds.tuxbuild.com/1vPdog8PxdjPNSB2wMWiinl6qCr/build.log
