### ISSUE TITLE
boot test defconfig+sanitizers

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/continuous-integration2#169]
we should boot test asan, ubsan, and friends

**Comment by nathanchance** [comment]
WIP: https://github.com/nathanchance/continuous-integration2/commit/e9416649764dee6502218dddf2f090334a28b037

KASAN KUnit tests are failing for at least x86_64 but that is not clang specific: https://lore.kernel.org/r/YQXMHnWRsmfzKK00@archlinux-ax161/

Certain arm64 builds with KASAN panic with ToT LLVM but my `module_{c,d}tor` linker script patch fixes that, leading me to believe that the sections might be getting placed too far away without that change.

**Comment by nickdesaulniers** [comment]
https://github.com/ClangBuiltLinux/linux/issues/1432 is fixed (mainline+)
