### ISSUE TITLE
lld tier not setting CC=clang?

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/continuous-integration2#174]
not sure if this is a problem or not, but I noticed we have a "tier" that's `LLD`. It doesn't set CC=clang. Not sure if that means we're not building these with clang?

**Comment by nathanchance** [comment]
`CC=clang` gets set because of the `toolchain` field: https://builds.tuxbuild.com/1vsPwCRuUsWp4pL9D2J4GlnvDOP/build.log
