### ISSUE TITLE
failure to clone

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/continuous-integration2#175]
the LTO tree builds are red: https://github.com/ClangBuiltLinux/continuous-integration2/runs/3167303143?check_suite_focus=true

    "git_sha": "438b498632d1430916ae87695dedc32b0d39f865",
    "status_message": "specified sha '438b498632d1430916ae87695dedc32b0d39f865' does not exist",

I don't think we specified the sha, just wanted master.  Did @samitolvanen  force push between when the CI started and when the job kicked off? Or did something go wrong with tuxsuite? cc @vishalbhoj

**Comment by nathanchance** [comment]
This is a problem on the TuxSuite backend. Sorry, thought I cc'd you on https://gitlab.com/Linaro/tuxsuite/-/issues/125

**Comment by nathanchance** [comment]
This has not happened since Vishal commented on the upstream issue so closing this one out.
