### ISSUE TITLE
Handle transition from LLVM 13 to LLVM 14

### ISSUE THREAD

**Issue by nathanchance** [ClangBuiltLinux/continuous-integration2#176]
The `release/13.x` branch has been cut meaning `clang-nightly` will now be `clang-14` and there will eventually be `clang-13` through [apt.llvm.org](https://apt.llvm.org/). The transition plan:

- [x] Wait for LLVM 13 binaries on [apt.llvm.org](https://apt.llvm.org/) ([done](https://lore.kernel.org/r/89b3f65d-b2c8-bd39-24a6-fd6b7f146a98@mozilla.com/))
- [x] Report availability of LLVM 13 binaries on [apt.llvm.org](https://apt.llvm.org/) to [TuxMake issue tracker](https://gitlab.com/Linaro/tuxmake) ([done](https://gitlab.com/Linaro/tuxmake/-/issues/154))
- [x] Wait for TuxMake to provide `clang-13` images ([done](https://gitlab.com/Linaro/tuxmake/-/commit/ffe969123598db11fbe196bd211385472f8485fe))
- [x] Wait for TuxSuite to allow `clang-13` to be specified ([done](https://gitlab.com/Linaro/tuxsuite/-/issues/129))
- [x] Update `generator.yml` to shift `llvm_tot` to 14 ([done](https://github.com/ClangBuiltLinux/continuous-integration2/pull/179))
- [x] Update `generator.yml` to shift `llvm_latest` to 13 and copy all `llvm_tot` builds to it ([done](https://github.com/ClangBuiltLinux/continuous-integration2/pull/179))
- [x] Update `generator.yml` to provide `llvm_12` anchor and copy all `llvm_latest` builds to it ([done](https://github.com/ClangBuiltLinux/continuous-integration2/pull/179))

cc @terceiro

**Comment by terceiro** [comment]
ack. I'm watching this and will do the tuxmake side when appropriate

**Comment by nathanchance** [comment]
41fc75f3c2d4a5439d6bb1a7088c6853ee9ae57d
