### ISSUE TITLE
Enable RISCV builds

### ISSUE THREAD

**Issue by nathanchance** [ClangBuiltLinux/continuous-integration2#18]
This will be blocked on `tuxbuild` upstream: https://gitlab.com/Linaro/tuxbuild/-/issues/91

We need `LD=riscv64-linux-gnu-ld` because `ld.lld` does not support linker relaxation (https://github.com/ClangBuiltLinux/linux/issues/1020).

Additionally, we will need to `kconfig: [defconfig, "CONFIG_EFI=n"]` to workaround https://github.com/ClangBuiltLinux/linux/issues/1143.

**Comment by nathanchance** [comment]
```
- {git_repo: "https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git", git_ref: "master", target_arch: riscv, toolchain: clang-nightly, kconfig: [defconfig, CONFIG_EFI=n], make_variables: {LD: riscv64-linux-gnu-ld, LLVM: 1, LLVM_IAS: 1}}
```

works for the build set. However, I am not sure how that should be represented in `generator.yml`.

**Comment by gctucker** [comment]
See also: https://groups.io/g/kernelci/message/994

As much as possible, it would be good to avoid duplicated efforts with KernelCI builds and other automated build system integrations.  Feel free to rely on the KernelCI Clang RISC-V builds as a reference if that helps, here's one:
https://kernelci.org/build/id/600a86edbd0ff54f40bb5d21/

It required this change in the Dockerfile: https://github.com/kernelci/kernelci-core/commit/1917b2ca0e3b4d44a27168303b9b6b2eb729bffd

We're gradually adding more architectures, let's hope we can keep sharing tips.

**Comment by nathanchance** [comment]
https://github.com/nathanchance/continuous-integration2/commit/958a202c03771b98472a0af802477ce4866f5003
