### ISSUE TITLE
GitHub Actions jobs per matrix limit

### ISSUE THREAD

**Issue by nathanchance** [ClangBuiltLinux/continuous-integration2#188]
If I read [GitHub Actions' usage limits](https://docs.github.com/en/actions/reference/usage-limits-billing-and-administration#usage-limits) correctly, I think we are about to hit the jobs per matrix limit on both linux-next and mainline:

```
$ begin; set -l workflow; for workflow in .github/workflows/*.yml; set -l jobs (rg "  _|  kick" $workflow &| wc -l); echo "$workflow has $jobs jobs"; end; end
.github/workflows/4.4.yml has 7 jobs
.github/workflows/4.9.yml has 9 jobs
.github/workflows/4.14.yml has 13 jobs
.github/workflows/4.19.yml has 13 jobs
.github/workflows/5.4.yml has 21 jobs
.github/workflows/5.10.yml has 94 jobs
.github/workflows/android-4.9.yml has 9 jobs
.github/workflows/android-4.14.yml has 9 jobs
.github/workflows/android-4.19.yml has 9 jobs
.github/workflows/android-mainline.yml has 18 jobs
.github/workflows/android12-5.4.yml has 18 jobs
.github/workflows/android12-5.10.yml has 18 jobs
.github/workflows/android13-5.10.yml has 18 jobs
.github/workflows/arm64-fixes.yml has 20 jobs
.github/workflows/arm64.yml has 20 jobs
.github/workflows/clang-version.yml has 0 jobs
.github/workflows/lint.yml has 0 jobs
.github/workflows/lto-cfi-tip.yml has 4 jobs
.github/workflows/lto-cfi.yml has 4 jobs
.github/workflows/mainline.yml has 227 jobs
.github/workflows/next.yml has 252 jobs
.github/workflows/tip.yml has 22 jobs
```

I guess at that point, it is probably worth splitting these up by `defconfig`, `all*configs`, and distro configs, unless anyone else has a better idea.

**Comment by nickdesaulniers** [comment]
256 is the limit? That's a very handy oneliner; I wonder if we should run that on pre-submit for PRs?

**Comment by nathanchance** [comment]
> 256 is the limit?

Looks like it. I almost want to try merging #187 to see what happens...

> That's a very handy oneliner; I wonder if we should run that on pre-submit for PRs?

Good call, done: https://github.com/ClangBuiltLinux/continuous-integration2/pull/191

**Comment by nickdesaulniers** [comment]
> Looks like it. I almost want to try merging #187 to see what happens...

We can try it just to see what happens? 🤷

**Comment by nathanchance** [comment]
We have a precommit check for this now; if we ever run over that matrix limit, we can look into splitting up the matrix by type (`defconfigs`, `allconfigs`, `distro_configs`) or by compiler version.
