### ISSUE TITLE
Improve problem matchers

### ISSUE THREAD

**Issue by nathanchance** [ClangBuiltLinux/continuous-integration2#192]
It is hard to see certain issues such as linker failures with the current problem matchers. We should try to improve them so that we can easily triage failures.

**Comment by nickdesaulniers** [comment]
see @kees ' #192

**Comment by kees** [comment]
Closing for now (since linker problems should be caught with PR #211 )

Future improvements may be wanted for objtool and modpost, but these should likely be separate Issues.
