### ISSUE TITLE
each QEMU log line followed by a blank line

### ISSUE THREAD

**Issue by kees** [ClangBuiltLinux/continuous-integration2#209]
The QEMU boot test output is kind of annoying to read with the repeated trailing blank lines. I assume this is github action logging translating "\r" into a full newline, but I haven't verified this. It should be possible to either switch the line-ending mode QEMU is using, or externally filter "\r\n" into "\n".

**Comment by nickdesaulniers** [comment]
@khilman @gctucker is this something you all have run into with the output from QEMU in KernelCI?

**Comment by kees** [comment]
Oh! No,it appears to have been a problem with the flushing (or maybe the unbuffer wrapper). This is fixed now after pull request #201 .
