### ISSUE TITLE
retry logic

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/continuous-integration2#213]
we need some retry logic to not fail the build when we fail to fetch logs or images. examples:
https://github.com/ClangBuiltLinux/continuous-integration2/runs/3700664838?check_suite_focus=true
```
raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 110] Connection timed out>
```
https://github.com/ClangBuiltLinux/continuous-integration2/runs/3700343954?check_suite_focus=true
```
ConnectionResetError: [Errno 104] Connection reset by peer
```
probably should implement expenontial backoff, too, and an upper threshold.

**Comment by nathanchance** [comment]
So I assume this would look something like actually checking the URLError number and retrying if it were 104 or 110, up to five times or some number that we determine?

Tangentially, these errors seem more numerous now, is this a TuxSuite issue?

**Comment by kees** [comment]
Maybe replace with `wget --tries=N` ?

**Comment by vishalbhoj** [comment]
I have been analyzing the infrastructure if there is anything from TuxSuite end that we could do to improve this. After tracing the failure, I found out that 5xx errors happening from AWS storage service. The recommendation for such failures is to do an exponential backoff and retry mechanism[1]. We also use the same in tuxsuite cli while posting any requests to the API.

[1] https://aws.amazon.com/premiumsupport/knowledge-center/http-5xx-errors-s3/
