### ISSUE TITLE
check_logs.py does not download the right binary for LLVM 11

### ISSUE THREAD

**Issue by nathanchance** [ClangBuiltLinux/continuous-integration2#22]
See https://github.com/ClangBuiltLinux/continuous-integration2/runs/1693329903.

`ARCH=arm LLVM=1 LLVM_IAS=1 BOOT=1 LLVM 11 multi_v5_defconfig`:

```
Linux version 5.11.0-rc3 (tuxmake@767e6ac67d3d) (Debian clang version 12.0.0-++20210109111114+9e4eadeb135d-1~exp1~20210109101808.3712, LLD 12.0.0) #2 PREEMPT Wed Jan 13 06:47:37 UTC 2021
```

I assume the toolchain version is not being taken into account but I have not looked.

**Comment by nickdesaulniers** [comment]
https://github.com/ClangBuiltLinux/continuous-integration2/blob/64f2aa239ae4caaf330fc1c669cd399fc1bf50f9/utils.py#L72-L78

is brittle and needs to be updated, now that we properly encode the LLVM version in the workflow yaml.
