### ISSUE TITLE
add coverage of 5.15

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/continuous-integration2#234]
both stable and android-common trees

I suspect this may be the next LTS release.

**Comment by nathanchance** [comment]
It is: https://www.kernel.org/category/releases.html

**Comment by nickdesaulniers** [comment]
woah, 4.4 support ending next year...I didn't think I'd live to see the day...

**Comment by nickdesaulniers** [comment]
reopening to track adding badges
