### ISSUE TITLE
extra newlines printed when printing clang info

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/continuous-integration2#235]
example: https://github.com/ClangBuiltLinux/continuous-integration2/runs/4112552575?check_suite_focus=true
```
Printing clang-nightly checkout date and hash

current date: Fri Nov  5 01:54:05 UTC 2021

clang checkout date: Tue Nov  2 07:17:12 UTC 2021

clang revision: 869989dd713d

clang revision link: https://github.com/llvm/llvm-project/commit/869989dd713d

5 warnings, 1 errors
```

**Comment by nathanchance** [comment]
Are you referring to the extra space between `Nov` and `5 01...`? That is just how `date` is but I guess I can just `sed` it out.

**Comment by nickdesaulniers** [comment]
@nathanchance sorry, not whitespace, I meant newlines.

**Comment by nathanchance** [comment]
Ah. I guess I find it easier to read with spaces between each item but I can remove that if you don't.
