### ISSUE TITLE
distro configs

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/continuous-integration2#25]
@nathanchance suggests fetching distros' configs and building those

**Comment by nathanchance** [comment]
Fedora and OpenSUSE would probably be a good place to start, given that their configs are available via URLs:

https://src.fedoraproject.org/rpms/kernel/tree/rawhide

https://github.com/openSUSE/kernel-source/tree/master/config

**Comment by nathanchance** [comment]
Blocked on https://gitlab.com/Linaro/tuxsuite/-/issues/124.
