### ISSUE TITLE
Explore moving to a container for boot testing

### ISSUE THREAD

**Issue by nathanchance** [ClangBuiltLinux/continuous-integration2#259]
Right now, we boot test kernels in Ubuntu 20.04, which has older versions of QEMU; we need a newer QEMU to boot s390 containers, which we maintain in [qemu-binaries](https://github.com/ClangBuiltLinux/qemu-binaries).

With GitHub Actions, we have [the ability to run these jobs in a container](https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#jobsjob_idcontainer), meaning we could use a newer version of distributions like Debian or Ubuntu or use a rolling release distribution such as Arch or OpenSUSE Tumbleweed to get constant version updates. The additional benefit of this is that we would not have to download the necessary packages for each job we run (which can result in occasional transient failures), they would already be installed.

GitHub has [a container registry](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry) so we would not have to use Docker Hub and it [integrates nicely](https://docs.github.com/en/actions/publishing-packages/publishing-docker-images) with GitHub Actions.

**Comment by ojeda** [comment]
+1, we are also considering doing the same for Rust for Linux, mainly for the speed (assuming it ends up being faster).

(We also have pre-built QEMU binaries in another repo too!)

**Comment by nickdesaulniers** [comment]
> mainly for the speed (assuming it ends up being faster).

Right, I guess the only thing I'm particularly curious about is the difference in time it takes to run the tests, if any?

**Comment by nathanchance** [comment]
GitHub Actions logs the time for each step so we could look at see if there is any change after that. Even if there isn't, I still think this is worth doing for more control over our test environment (as we are not tied to Ubuntu QEMU versions).

**Comment by nathanchance** [comment]
Well, that was pretty simple...

https://github.com/ClangBuiltLinux/containers

https://github.com/ClangBuiltLinux/containers/pkgs/container/qemu

```
$ podman pull ghcr.io/clangbuiltlinux/qemu
Trying to pull ghcr.io/clangbuiltlinux/qemu:latest...
Getting image source signatures
Copying blob 15dd5e5b37a1 skipped: already exists
Copying blob a30a01d1eaab skipped: already exists
Copying blob 07740722bc45 done
Copying config fd8f750432 done
Writing manifest to image destination
Storing signatures
fd8f7504323740c942b9cac95659ccd75de18846cdebcbfc13d57b9125863630

$ podman run --rm -ti -v "$CBL_GIT/boot-utils:/boot-utils" -v "$CBL_SRC/linux:/linux" ghcr.io/clangbuiltlinux/qemu /boot-utils/boot-qemu.sh -a ppc32 -k /linux -t 30s
QEMU location: /usr/sbin

QEMU version: QEMU emulator version 6.2.0
...
Linux version 5.16.0-rc7-00011-g6966da86d83b (nathan@archlinux-ax161) (ClangBuiltLinux clang version 14.0.0 (https://github.com/llvm/llvm-project 71b3bfde9cd296525bbf5b1619e199074156d12b), LLD 14.0.0) #1 Thu Dec 30 21:32:57 UTC 2021
...
```

**Comment by nathanchance** [comment]
Some successful runs:

https://github.com/ClangBuiltLinux/continuous-integration2/actions/runs/1661004938

https://github.com/ClangBuiltLinux/continuous-integration2/actions/runs/1660949763

**Comment by nickdesaulniers** [comment]
yeah looks great!
