### ISSUE TITLE
Cron schedule

### ISSUE THREAD

**Issue by nathanchance** [ClangBuiltLinux/continuous-integration2#3]
@nickdesaulniers had suggested adding a `cron` option in the `configurator.yml` so that different trees can be run at different frequencies via the GitHub Actions `cron:` option: https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#scheduled-events

`mainline` and the `android-*` trees see fairly regular development so doing these every six hours or so would probably be a good starting point.

`next` is updated only once a day so that should be done daily.

`stable` updates do not happen more than once a week usually but keeping them daily is still a good idea to try and catch compiler regressions.

**Comment by nickdesaulniers** [comment]
I think once https://gitlab.com/Linaro/tuxbuild/-/issues/79 is fixed, I'd like to modify the generator.yml to list frequencies and the command line parameters to the generators to accept frequencies for the cron jobs, rather than a branch. (cc @danrue )

**Comment by nathanchance** [comment]
https://github.com/nathanchance/continuous-integration2/commit/8511de20ffdfb5d45702f8c4155ad1f1cd95e7e0

**Comment by nickdesaulniers** [comment]
that looks nice. Does next get updated on the weekends? If not, we could express that in cron even.
