### ISSUE TITLE
fix badge sort order

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/continuous-integration2#303]
forked from https://github.com/ClangBuiltLinux/continuous-integration2/pull/301#pullrequestreview-885178529

**Comment by nathanchance** [comment]
I think Kees' rewrite resolved this? https://github.com/ClangBuiltLinux/continuous-integration2/commit/49c5d6d847ad62f52754eaf23ef4d32ec7047f11
