### ISSUE TITLE
Full LTO builds getting killed again?

### ISSUE THREAD

**Issue by nathanchance** [ClangBuiltLinux/continuous-integration2#315]
Over the past few days, I have noticed that certain builds are being killed, presumably due to full LTO and high memory usage. This was brought up in #105, with a swap file being used to work around it. Does the file need to be increased?

https://builds.tuxbuild.com/25j2GVvoQebF4l5F1vi8v1MvPjl/build.log
https://builds.tuxbuild.com/25Xu2bS48Uc0wjzKwR8vAwQ0l5S/build.log

cc @vishalbhoj (I can file this on the TuxSuite issue tracker if that is preferred?).

**Comment by vishalbhoj** [comment]
@nathanchance  thanks for reporting it. I'll increase the swap size and rerun the build and check if that solves the issue.

**Comment by vishalbhoj** [comment]
@nathanchance I have increased the swap space and the above build when resubmitted finished successfully: https://builds.tuxbuild.com/25mSJZnL24KjWQk3RtlRnpBOGVw/

**Comment by nathanchance** [comment]
Great, thank you so much! I'll monitor the builds over the next few days and I'll reopen this if it happens again.
