### ISSUE TITLE
android-4.9 + clang-13 "Inconsistent kallsyms data"

### ISSUE THREAD

**Issue by nathanchance** [ClangBuiltLinux/continuous-integration2#316]
https://github.com/ClangBuiltLinux/continuous-integration2/runs/5354761534?check_suite_focus=true

```
$ make -skj"$(nproc)" ARCH=arm64 CC=clang CROSS_COMPILE=aarch64-linux-gnu- mrproper cuttlefish_defconfig all
...
Inconsistent kallsyms data
Try make KALLSYMS_EXTRA_PASS=1 as a workaround
...
```

According to [the workflow history](https://github.com/ClangBuiltLinux/continuous-integration2/actions/workflows/android-4.9-clang-13.yml) and metadata from the [last passing build](https://builds.tuxbuild.com/25UnYYHbzagTPIXbB7ZG0sKeNDL/metadata.json) and the [first failing build](https://builds.tuxbuild.com/25XhFZXBNtBJN3J8D8FMBh9SAYN/metadata.json), all that changed was a stable merge (i.e., no compiler change because it is LLVM 13.0.1).

I am able to reproduce this with LLVM 13.0.1 (top of `release/13.x`) but not LLVM 13.0.0 (`llvmorg-14-init^`). I bisected it down to https://github.com/llvm/llvm-project/commit/52a400d8e4c46876fae5d732c92df254a9ceae8f. Since there is currently no issue with [`android-4.9` + `release/14.x`](https://github.com/ClangBuiltLinux/continuous-integration2/actions/workflows/android-4.9-clang-14.yml) nor [`android-4.14` + `release/13.x`](https://github.com/ClangBuiltLinux/continuous-integration2/actions/workflows/android-4.14-clang-13.yml), I can only assume that either something is missing from the backport in LLVM (unknown dependency?), there is something that changed between 4.9 and 4.14 that prevents this from triggering, or we are missing a backport from 4.9 that is present in 4.14 and newer.

Investigating the kernel differences is going to be rather difficult, considering that clang cross compiling support was not merged until 4.14 and was not backported to a stable release.

**Comment by nickdesaulniers** [comment]
> I bisected it down to https://github.com/llvm/llvm-project/commit/52a400d8e4c46876fae5d732c92df254a9ceae8f.

That change will perturb inlining decisions. My money is on missing backport that is present in 4.14+.

**Comment by nathanchance** [comment]
So, this disappeared with the 4.9.304 merge...

https://github.com/ClangBuiltLinux/continuous-integration2/runs/5428154064?check_suite_focus=true

*shrug*

I will investigate this if it shows up again. Given that 4.9 is only supported for another year, I am not inclined to spend a whole ton of time trying to figure out what we are missing, especially since `clang-14` and beyond are fine.
