### ISSUE TITLE
test cros trees

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/continuous-integration2#328]
I'd like to get to the point where we can find+fetch CrOS kernel trees and build those in CI.

@m-gupta / @groeck do you have the git URLs for CrOS' kernel trees?

**Comment by nathanchance** [comment]
Should be https://chromium.googlesource.com/chromiumos/third_party/kernel/, right?

**Comment by nathanchance** [comment]
https://gitlab.com/Linaro/tuxsuite/-/issues/156 is resolved so I pushed https://github.com/ClangBuiltLinux/continuous-integration2/pull/362.
