### ISSUE TITLE
arm64 allmodconfig timeout with clang-12

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/continuous-integration2#347]
I'm not sure precisely what failed here.
https://github.com/ClangBuiltLinux/continuous-integration2/runs/5746844441?check_suite_focus=true

> 🔧 Infrastructure Error, Please retry - retrying (attempt 2/3): e29be6724adb ("Linux 5.15.32") arm64 (allmodconfig+4) with clang-12 @ https://builds.tuxbuild.com/275Nz0KMPfBaGyjemm0sHJySCRb/

cc @vishalbhoj

**Comment by vishalbhoj** [comment]
@nickdesaulniers It was an infrastructure issue with AWS. There were 6 machines provisioned but in a limbo state which affected our autoscaler calculation. This effectively caused this particular build to be in queue for a long duration. The cli was still waiting for this build to complete but github cancelled the action after 6 hour timeout.

**Comment by nathanchance** [comment]
Not much to do here I think?
