### ISSUE TITLE
properly escape cron string

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/continuous-integration2#37]
pretty sure that's why the github action isn't running overnight; the string needs to be quoted.  Nothing I can come up with in job_fragment.yml seems to quote the string properly..

**Comment by nathanchance** [comment]
The cron did run today. See the [Actions tab](https://github.com/ClangBuiltLinux/continuous-integration2/actions) where you can see that they were "scheduled".

**Comment by nickdesaulniers** [comment]
oh, I guess maybe a timezone issue then; I expected midnight, but I guess midnight from another timezone makes sense.
