### ISSUE TITLE
Error: make variable 'LLVM' value invalid '0'

### ISSUE THREAD

**Issue by nathanchance** [ClangBuiltLinux/continuous-integration2#39]
Looks like something might have changed on the TuxSuite side of things: https://github.com/ClangBuiltLinux/continuous-integration2/runs/1745918086?check_suite_focus=true

```
Error: make variable 'LLVM' value invalid '0'
```

However, I think that they did us a favor. `LLVM=0` and `LLVM=1` are technically equivalent: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/Makefile#n428?h=v5.11-rc4

I think that the way that we generate `make_variables` in the tuxsuite files from `generator.yml` needs to change. Currently, we rely on the `llvm` and `llvm_ias` values but I think that this is too rigid. We have three general levels of support:

* `CC=clang` (`make_variables` is empty/non-existent)
* `LLVM=1` (`make_variables: {LLVM: 1}`)
* `LLVM=1 LLVM_IAS=1` (`make_variables: {LLVM: 1, LLVM_IAS: 1}`)

but there are also instances where we need to add another variable, like `LD` for riscv. I am just not sure what the best way to do this is though.

**Comment by nickdesaulniers** [comment]
> CC=clang (make_variables is empty/non-existent)

Shouldn't that be `make_variables: {CC: clang}`?

I think in generator.yml, we could define

```yaml
tiers:
  LLVM_full:
    LLVM: 1
    LLVM_IAS: 1
  LLVM:
    LLVM: 1
  LLD:
    CC: clang
    LD: ld.lld
```
then refer to `<<: *LLVM_full` in the builds.

**Comment by nathanchance** [comment]
`clang-nightly` implicitly passes `CC=clang` to `make` so we do not need to specify anything. But yes, I think the tiers idea generally makes sense then we could add a RISCV one that we could use across all of the RISCV lines.
