### ISSUE TITLE
s390 boot failures with mainline

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/continuous-integration2#450]
looks like
- [clang-14](https://github.com/ClangBuiltLinux/continuous-integration2/actions/runs/3172033819/jobs/5166528970)
- [clang-15](https://github.com/ClangBuiltLinux/continuous-integration2/actions/runs/3172015719/jobs/5166444131)
- [clang-16](https://github.com/ClangBuiltLinux/continuous-integration2/actions/runs/3172089484/jobs/5167664830)
are failing to boot mainline.

Is this related to the recent QEMU bug, or perhaps a new failure?

**Comment by nickdesaulniers** [comment]
Adding context from IRC. @nathanchance reminds me that our qemu image we use in CI is built from arch-linux.
https://github.com/ClangBuiltLinux/containers/blob/438e8c66db38a56d210a32021a182e815b569a1b/qemu/Dockerfile

**Comment by nathanchance** [comment]
https://github.com/ClangBuiltLinux/containers/commit/879be368a87b7c1605ebba2b143a2ca4562d0512 should resolve this. It might take a little bit for everything to get healthy again, feel free to reopen if it regresses again.
