### ISSUE TITLE
enable LTO for riscv

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/continuous-integration2#453]
I don't see it pushed to [the riscv tree](https://git.kernel.org/pub/scm/linux/kernel/git/riscv/linux.git/) yet, but [LTO for riscv is coming](https://lore.kernel.org/llvm/mhng-e9b5bd39-0929-487c-a761-6a3ff508d969@palmer-ri-x1c9/).

**Comment by nickdesaulniers** [comment]
wonder if this has landed yet?
https://lore.kernel.org/llvm/20220512205545.992288-1-twd2.me@gmail.com/

**Comment by nathanchance** [comment]
I don't see it on any branch in https://git.kernel.org/pub/scm/linux/kernel/git/riscv/linux.git/ nor in mainline.

**Comment by nickdesaulniers** [comment]
cc @twd2

**Comment by twd2** [comment]
I saw my patch was once applied to `for-next` but later that commit was removed from the tree. 
Is there anything I can improve? @palmer-dabbelt

**Comment by nathanchance** [comment]
@twd2 I sent a ping for it recently but I think it might just be better to resend the patch at this point. The RISC-V folks [recently went back to tracking patches via Patchwork](https://lore.kernel.org/20221011160744.2167025-1-conor@kernel.org/), which should help ensure the patch does not get lost (as well as make it obvious to you when it has been picked up).

**Comment by nathanchance** [comment]
I sent v3 due to `arch/riscv/kernel/pi` needing LTO disabled: https://lore.kernel.org/20231003-riscv-lto-v3-1-8aca61a4ecb4@kernel.org/

**Comment by twd2** [comment]
Cool! Thanks!

**Comment by nathanchance** [comment]
This has been accepted and is now available in -next, so we should be able to get this wired up there:

https://git.kernel.org/next/linux-next/c/021d23428bdbae032294e8f4a29cb53cb50ae71c
