### ISSUE TITLE
arm64-fixes breakage

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/continuous-integration2#455]
[arm64-fixes](https://github.com/ClangBuiltLinux/continuous-integration2/actions/runs/3193823102/jobs/5212775945) is failing with https://github.com/ClangBuiltLinux/linux/issues/1686, but [the tuxsuite](https://github.com/ClangBuiltLinux/continuous-integration2/actions/runs/3193823102/jobs/5212776021) parent job invocation shows that `--patch-series patches/arm64-fixes` was set.

I wonder what happened?

**Comment by nathanchance** [comment]
This appears to be a TuxSuite bug, as we can clearly see the `--patch-series` flag is being passed along to `tuxsuite plan` but there is no indication that the patches are being applied.

Filed upstream: https://gitlab.com/Linaro/tuxsuite/-/issues/178

**Comment by nathanchance** [comment]
This should now be resolved on the TuxSuite side: https://gitlab.com/Linaro/tuxsuite/-/commit/f357f8a8fd1399f29ed2d22b2398994ec58ab72c
