### ISSUE TITLE
corrupt, or missing json?

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/continuous-integration2#457]
a couple tip builds failed to parse json:

https://github.com/ClangBuiltLinux/continuous-integration2/actions/runs/3237039735/jobs/5307262986

we can probably better handle `JSONDecodeError` then dump the output. That would help us figure out if the error was in the status.json or what.

**Comment by nathanchance** [comment]
The output size of `output_artifact_allconfigs` in the GitHub UI is 0 bytes and `builds.json` is completely empty when I inspect it locally, which makes it seem like this is a TuxSuite issue.

**Comment by nathanchance** [comment]
https://gitlab.com/Linaro/tuxsuite/-/issues/179
