### ISSUE TITLE
add button for check-clang-version

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/continuous-integration2#478]
https://github.com/ClangBuiltLinux/continuous-integration2/actions/workflows/clang-version.yml has been red but we didn't notice because it's not in the grid of buttons we check in the readme or homepage.  Probably doesn't need to be in the grid, but we should have an "indicator light" somewhere.

**Comment by sylvestre** [comment]
My bad:
`clang hasn't been updated in 25 days!`

I have some issues that I don't know how to fix:
https://github.com/llvm/llvm-project/issues/59097

**Comment by nathanchance** [comment]
> My bad: `clang hasn't been updated in 25 days!`

To be fair, the reason for that is not entirely your fault :) TuxMake's images have been failing to build for three weeks now, which was before apt.llvm.org started failing:

https://gitlab.com/Linaro/tuxmake/-/issues/196

**Comment by sylvestre** [comment]
I fixed the issue on my side. we should be up to date now on all branches!
