### ISSUE TITLE
x86_64 allyesconfig builds of stable timing out

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/continuous-integration2#539]
https://github.com/clangbuiltlinux/continuous-integration2/actions/workflows/stable-clang-17.yml

for 3 weeks now this has been timing out

**Comment by nathanchance** [comment]
This is due to https://github.com/ClangBuiltLinux/linux/issues/1768 (I note in that issue why this is specific to `clang-15`+). We need Peter's series to be backported to 6.2 in order to fix this (or we can just disable `allyesconfig` for stable until it is updated to 6.3 in a few weeks).

**Comment by nickdesaulniers** [comment]
Let's disable it for now then.
