### ISSUE TITLE
build.log not fetched/displayed

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/continuous-integration2#540]
https://github.com/ClangBuiltLinux/continuous-integration2/actions/runs/4527641306/jobs/7974728249#step:5:145  failed but did not print build.log.

https://storage.tuxsuite.com/public/clangbuiltlinux/continuous-integration2/builds/2NZv76Eis4NY8IEdQXmbhTNB59c/ should be the artifact for that build. Looks like it wasn't even fetched?

**Comment by nathanchance** [comment]
We only print `build.log` if `errors_count` or `warnings_count` is greater than 0, which you can see from the JSON print out is not true. We can just adjust that condition to include if the build failed.

**Comment by nickdesaulniers** [comment]
I'm inclined to treat this as a tuxsuite issue then; if the linker prints an error, then tuxsuite needs to set that in the metadata.json.

**Comment by nickdesaulniers** [comment]
https://gitlab.com/Linaro/tuxsuite/-/issues/188

**Comment by nathanchance** [comment]
The issue has been resolved upstream.
