### ISSUE TITLE
Failed ChromeOS jobs on April 8th

### ISSUE THREAD

**Issue by nathanchance** [ClangBuiltLinux/continuous-integration2#549]
One example:

https://github.com/ClangBuiltLinux/continuous-integration2/actions/runs/4648117706

Seems like another caching run is needed?

cc @vishalbhoj

**Comment by vishalbhoj** [comment]
Hi Nathan,

Yes this is again a caching issue. The chromiumos kernel tree is the largest and with git operations the disk usage grows very quickly. I have cleaned up the cache again to make it functional. I'll work on handling it better and post back on this issue.

**Comment by nathanchance** [comment]
I have not seen this occur recently, so I am closing this up for now.
