### ISSUE TITLE
panics not being caught in ci

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/continuous-integration2#553]
https://github.com/ClangBuiltLinux/boot-utils/pull/95 was meant to address this, but
https://github.com/ClangBuiltLinux/continuous-integration2/actions/runs/4729226155/jobs/8392326831
is still failing.
Do we need to uprev boot-utils in ci?

**Comment by nathanchance** [comment]
> is still failing

You mean not failing? :)

> Do we need to uprev boot-utils in ci?

Yes, I did not to uprev boot-utils without a fix for the panics in sight, since that will make the builds go red (even though they obviously should be). I'll update it today.
