### ISSUE TITLE
die__process_unit: DW_TAG_label ... not handled!

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/continuous-integration2#568]
Forked from https://github.com/ClangBuiltLinux/linux/issues/1723

We'll continue to observe this until pahole 1.25 is released (by [Debian](https://gitlab.com/Linaro/tuxmake/-/issues/204#note_1392068844), https://lore.kernel.org/all/ZDG4qxirpIfmbiip@kernel.org/ is the upstream release) then shipped by tuxsuite.
https://gitlab.com/Linaro/tuxmake/-/issues/204

**Comment by nathanchance** [comment]
TuxSuite should be using pahole 1.25 now: https://gitlab.com/Linaro/tuxmake/-/commit/b9f7f26fa8534f243c0bc20ad7ac782ba730cc3d
