### ISSUE TITLE
matchers matching multiple times

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/continuous-integration2#571]
Consider https://github.com/ClangBuiltLinux/continuous-integration2/actions/runs/5063397137.

The ARCH=arm related issue is reported 10 times, but there's not 10 boot failures. All reports go to the same link. Is there a bug in the matcher?

**Comment by nathanchance** [comment]
We do not just match on boot failures, we match on build errors. It should be this matcher I think: https://github.com/ClangBuiltLinux/continuous-integration2/blob/main/.github/problem-matchers/compiler-non-source.json

There are 10 error lines in there (two lines per crash and there are five crashes), so I do not think there is a bug here.

**Comment by nickdesaulniers** [comment]
Grepping the raw log for `error]clang: error` I see 18 hits. That looks like 9 crashes to me. So how do we get to 10 reports?

**Comment by nathanchance** [comment]
https://github.com/actions/toolkit/blob/main/docs/problem-matchers.md#limitations

> 10 warning annotations, 10 error annotations, and 10 notice annotations per step
