### ISSUE TITLE
856dd6c59812 for android-mainline

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/continuous-integration2#574]
thumb2 builds of android-mainline are failing
https://github.com/ClangBuiltLinux/continuous-integration2/actions/runs/5076729153/jobs/9120297489#step:5:1262
they need
commit 856dd6c59812 ("ext4: fix unused iterator variable warnings")
if android-mainline isn't updated soon.

**Comment by nathanchance** [comment]
I will give it a week to see if they can get close enough to 6.4-rc1 to include that change.
