### ISSUE TITLE
re-enable RELOCATABLE for loongarch

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/continuous-integration2#667]
https://github.com/ClangBuiltLinux/continuous-integration2/blob/5a5ca456a0a5ea6889b6cb25e4a13e1b6928b94e/generator.yml#L282C45-L285

https://github.com/ClangBuiltLinux/linux/issues/1883

**Comment by nathanchance** [comment]
We should be able to do this once the fix lands in stable. It has been AUTOSEL'd: https://lore.kernel.org/20231211135147.380223-45-sashal@kernel.org/

**Comment by nickdesaulniers** [comment]
Does the ld-option check have implications on a specific version LLD version?

**Comment by nathanchance** [comment]
It seems like LLD has supported this option for some time:

https://github.com/llvm/llvm-project/commit/64f65b02d287b760959e727d897cbeb3f8c50434

It also seems like GNU ld does not support this option for targets other than AArch64:

https://sourceware.org/bugzilla/show_bug.cgi?id=25891
