### ISSUE TITLE
Drop 4.14 (soon)

### ISSUE THREAD

**Issue by JustinStitt** [ClangBuiltLinux/continuous-integration2#675]
While it isn't [quite time yet](https://endoflife.date/linux), I'm opening this issue so we remember to drop 4.14 from CI in a few weeks (31 Jan 2024).

The introduction of the 6.6 LTS Kernel integration into CI (#673) means we have ramped up our total builds being ran. This will add a new row to the CI matrix, meaning more jobs and more clutter in the matrix itself.

While the CI caching helps here, especially for a kernel as old as 4.14, we should be prompt in dropping our CI support for it nonetheless.

edit:

... and also consider dropping android‑4.14 CI support

**Comment by nathanchance** [comment]
Thanks for opening this! It is actually sooner than you might think, 4.14.336 is out for review and Greg states that it is going to be the last 4.14 release: https://lore.kernel.org/20240108141854.158274814@linuxfoundation.org/

**Comment by nathanchance** [comment]
4.14 is officially EOL with 4.14.336:

https://git.kernel.org/pub/scm/docs/kernel/website.git/commit/?id=8ba05df34af92bc993c6e88393cd71e1516a99c6
https://lore.kernel.org/2024011046-ecology-tiptoeing-ce50@gregkh/
https://git.kernel.org/stable/l/linux-4.14.y

@JustinStitt want to take a crack at dropping 4.14 from CI? You can use the 4.9 EOL pull as a reference, should be mostly the same here: https://github.com/ClangBuiltLinux/continuous-integration2/commit/c3088308043c5c469fcbf3e034228271ed0488a6

**Comment by JustinStitt** [comment]
> @JustinStitt want to take a crack at dropping 4.14 from CI? You can use the 4.9 EOL pull as a reference, should be mostly the same here: https://github.com/ClangBuiltLinux/continuous-integration2/commit/c3088308043c5c469fcbf3e034228271ed0488a6


Yeah, I'll try to tackle that after lunch 👍
