### ISSUE TITLE
Update Website With CI Matrix

### ISSUE THREAD

**Issue by JustinStitt** [ClangBuiltLinux/continuous-integration2#677]
We need to update [clangbuiltlinux.github.io](https://clangbuiltlinux.github.io/) so that Kees' badging system can work (his tooling relies on the website rather than the repo).

@nathanchance

**Comment by nathanchance** [comment]
Grrr, should have done that yesterday :(

https://github.com/ClangBuiltLinux/ClangBuiltLinux.github.io/pull/62

Thanks!
