### ISSUE TITLE
Add clang-cfi tree

### ISSUE THREAD

**Issue by nathanchance** [ClangBuiltLinux/continuous-integration2#69]
We should add testing for @samitolvanen 's LTO/CFI tree. We can build both the mainline and tip based branches. TuxSuite has the ability to specify the additional configurations needed on top of a configuration as a URL or in the tree under `kernel/configs/`: https://gitlab.com/Linaro/tuxsuite#kconfig-examples

Sami, if you wanted to, you could add an arm64 and x86_64 configuration fragment in that folder with the options you want us to test.

**Comment by samitolvanen** [comment]
Sure. I'm currently running a CI locally, but more testing can't hurt. I'll take a look at adding the configs when I have a chance.

**Comment by samitolvanen** [comment]
I think we should be fine with ThinLTO and CFI, and both arm64 and x86_64 can use the same config fragments. How does that look?

**Comment by dileks** [comment]
On Wed, Feb 10, 2021 at 7:35 PM Sami Tolvanen <notifications@github.com>
wrote:

> I think we should be fine with ThinLTO and CFI, and both arm64 and x86_64
> can use the same config fragments. How does that look?
>

Last I looked at Clang-CFI it build and boot on bare metal on x86_64 - with
a slightly modified Debian-5.10 kernel-config for Linux v5.7-rcX.
So, GoGoGo.

**Comment by nathanchance** [comment]
> I think we should be fine with ThinLTO and CFI, and both arm64 and x86_64 can use the same config fragments. How does that look?

Yes, this is exactly what I had in mind, thank you :) if you feel like any other configurations are worth testing (like if there is a config that has been problematic in combination with LTO/CFI in the past), feel free to add more configuration fragments and we can turn those into separate build targets.

I will take it from here getting your tree added to the matrix!

**Comment by nathanchance** [comment]
@samitolvanen on your next push, would you mind adding that commit to the `tip/clang-cfi` branch as well? I'd like to add both branches since we have the capacity.

**Comment by samitolvanen** [comment]
Sure, added also to tip/clang-cfi.
