### ISSUE TITLE
Desync in Matrix Badges

### ISSUE THREAD

**Issue by JustinStitt** [ClangBuiltLinux/continuous-integration2#729]
I noticed that the state of Badges in the matrix is commonly out of sync with the recent workflow results. Not just by a few hours, but by days or weeks.

I assumed it was a browser cache issue but I cleared my browser's page cache. @nathanchance are you experiencing this as well?
<details open>

<summary>Gif</summary>
<br>
<img src="https://github.com/ClangBuiltLinux/continuous-integration2/assets/24460581/b928d6a9-8376-472d-8873-47936246f97c"></img>
</details>

**Comment by nathanchance** [comment]
I see the same behavior. Did the badge syncing break? cc @kees

**Comment by kees** [comment]
Everything I just checked is showing the correct colors. Which do you see as out of sync? Clang 18 mainline shows red for me on the README.

**Comment by nathanchance** [comment]
The failures in `chromeos-6.6`, `chromeos-6.1`, and `android15‑6.6` and the pass from mainline `clang-15` do not appear to be legitimate at the least.

**Comment by kees** [comment]
I wonder if this is a local vs server caching problem; I don't see any of what you see. Maybe I need to switch to copies of badges instead of symlinks.

**Comment by JustinStitt** [comment]
Hi, I haven't noticed this issue reoccurring in awhile. Maybe it was a GitHub thing. Anyways, closing for now.
