### ISSUE TITLE
touch workflow files

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/continuous-integration2#755]
I'm still getting lots of emails about the test failures. Looks like it's a case of whoever touched them last.

https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/notifications-for-workflow-runs

> Notifications for scheduled workflows are sent to the user who initially created the workflow. If a different user updates the cron syntax in the workflow file, subsequent notifications will be sent to that user instead.

@nathanchance do you mind `touch`ing the workflow files to take over the emails from failed test runs?

**Comment by nathanchance** [comment]
@nickdesaulniers Sure thing, although if I am reading that correctly, I think I will need to alter the `cron` field specifically. I'll do a mass update manually then revert it and see if that is enough to switch it over to me (honestly though, that behavior by GitHub kind of sucks, I wish we had the ability to specify recipients of failure emails like we did with Travis).
