### ISSUE TITLE
sparc testing

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/continuous-integration2#786]
https://lore.kernel.org/lkml/cfc033a8-a7de-469b-8afa-0069593c5c6f@gaisler.com/ makes it sound like support for ARCH=sparc is on its way to linux-next.  We probably can probably start build+boot testing this arch.

**Comment by nathanchance** [comment]
https://git.kernel.org/alarsson/linux-sparc/l/b6370b338e71cf24c61e33880b8f1a0dd5ad0a44

We will need to update TuxMake for this first: https://gitlab.com/Linaro/tuxmake/-/merge_requests/456

**Comment by nathanchance** [comment]
boot-utils PR: https://github.com/ClangBuiltLinux/boot-utils/pull/122
