### ISSUE TITLE
CONFIG_X86_X32

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/continuous-integration2#87]
we should test CONFIG_X86_32 as it's a curious configuration, via: https://lore.kernel.org/lkml/c0ff7dba14041c7e5d1cae5d4df052f03759bef3.1613243844.git.luto@kernel.org/.

**Comment by nickdesaulniers** [comment]
nvm I thought that thread was about CONFIG_X86_X32.  That's the config we should probably test.

**Comment by nathanchance** [comment]
We do test `CONFIG_X86_32` with `i386_defconfig`, do you mean `CONFIG_X86_X32`?

**Comment by nathanchance** [comment]
And that is what I get for trying to research and reply on my phone :P

**Comment by nathanchance** [comment]
We do test `CONFIG_X86_X32` as part of `all{mod,yes}config`. Do you want `x86_64_defconfig` + `CONFIG_X86_X32` then?

**Comment by nickdesaulniers** [comment]
oh, I didn't realize X32 is enabled via all*config.  Ok, then maybe defconfig+x32 doesn't add much signal then.
