### ISSUE TITLE
spin down LTO tree?

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/continuous-integration2#91]
now that LTO has been merged into mainline
1. https://lore.kernel.org/lkml/CAHk-=wgQ=oaLD_ybzhOP+8LFNZH3Qzpc-dp4XB4cXxXLReCdnQ@mail.gmail.com/
2. https://lore.kernel.org/lkml/161412339312.20258.3918342161141874906.pr-tracker-bot@kernel.org/

do we need to keep testing Sami's LTO trees? I suppose so for CFI?  Let's keep an eye out for any new breakages for all{yes|mod}config breakages that may result. cc @samitolvanen @nathanchance

**Comment by nathanchance** [comment]
Yes, we will want to keep these for CFI. Once that gets merged, we could just enable `CONFIG_LTO_CLANG_THIN` and `CONFIG_CFI_CLANG` in an anchor and build it on -next and mainline.
